stages:
  # 建立 rancher_pipeline 專用的 Docker Image
  - name: Publish apache service image
    steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        pushRemote: true
        registry: 10.20.0.73:5443
      env:
        PLUGIN_BUILD_ARGS: --progress=tty --network=host
        PLUGIN_DEBUG: "true"
        PLUGIN_INSECURE: "true"
        PLUGIN_MIRROR: https://10.20.0.73:5443
        PLUGIN_MTU: "1000"

  # 部屬 apache web
  - name: deploy--apache-editor
    steps:
    - applyYamlConfig:
        path: ./k8s-yaml/apacher-deployment.yaml
    - applyYamlConfig:
        path: ./k8s-yaml/apache-service.yaml
    #- applyYamlConfig:
    #    path: ./k8s-yaml/apache-ingress.yaml
